Through ALS, we are taking a matrix of user/item interactions and figuring out the latent features that relate them to each other. This matrix factorisation method reduces the dimensions/ features (while keeping relevant information) into a smaller matrix of user features and item features.

The matrix factorisation results is:
1. One smaller matrix with dimensions: num of users x latent feature --> contains latent user feature vectors for each user
2. And another matrix with dimensions: num of items x latent feature --> contains latent item feature vectors for each item

Multiplying these two feature matrices together approximates the original matrix, but now we have two matrices that are dense including a number of latent features for each of our items and users.

In [31]:
import pandas as pd
import numpy as np
import random
import scipy.sparse as sparse
from tqdm import tqdm_notebook as tqdm
import implicit
from sklearn.preprocessing import MinMaxScaler

In [32]:
df = pd.read_csv('../inputs/profile_features_clean.csv')

In [33]:
df.sample(5)

,account_balance,card_brand_users,has_coupon,birthday_year,birthday_month,age,user_id,address,zone_id,salesperson_id,...,delivery_order_id,item_id,item_type,quantity,unit_price,name,macros,ingredients,temperature,category
47865,0,Visa,0,NaN,NaN,NaN,33994,51 Kee Sun Avenue,61.0,0,...,98538,472.0,main,1.0,1395.0,Sous‑vide Turkey on Chilled Capellini,"Calories: 510, Protein: 50g, Fat: 14g, Carb: ...","capellini, sous-vide turkey, compressed shoyu ...",chilled,regular
10356,0,Visa,0,NaN,NaN,NaN,1548,One Raffles Quay taxi stand,74.0,0,...,9204,184.0,main,2.0,995.0,Spicy Quinoa and Oregano Sweet Potato Salad,"Calories: 408, Fat: 9g, Carb: 73g, Protein: 11g","sweet potato, quinoa, celery, sweet peas, rais...",chilled,main
51687,0,Visa,1,NaN,NaN,NaN,22629,20 Pasir Panjang Road,61.0,0,...,95643,459.0,main,5.0,950.0,Roasted Pumpkin and Black Rice Salad,"Calories: 575, Protein: 27.7g, Fat: 8.5g, Carb...","pumpkin, black rice, brown rice, sweet corn, c...",chilled,regular
12996,0,Visa,0,NaN,NaN,NaN,29110,407 Upper Changi Road North,61.0,0,...,76928,376.0,main,25.0,995.0,Grain Chicken Rice,"Calories: 517, Fat: 7g, Carb: 76g, Protein: 36g","chicken, brown rice, white rice, kailan, chick...",warm,regular
26509,0,Visa,0,NaN,NaN,NaN,28460,77 Ayer Rajah Crescent,61.0,0,...,105970,377.0,main,1.0,895.0,Dragon Well Basil Rice,"Calories: 495, Fat: 15g, Carb: 75g, Protein: 16g","brown rice, black rice, egg, white cabbage, ce...",warm,regular

In [34]:
df.dtypes

account_balance               int64
card_brand_users             object
has_coupon                    int64
birthday_year               float64
birthday_month              float64
age                         float64
user_id                       int64
address                      object
zone_id                     float64
salesperson_id                int64
discount                    float64
due_dates_only               object
card_details                 object
card_brand_delivery_info     object
source                       object
delivery_fee                float64
meal_wave                    object
surcharge_amount            float64
promo_code_used               int64
gave_feedback                 int64
district                    float64
delivery_order_id             int64
item_id                     float64
item_type                    object
quantity                    float64
unit_price                  float64
name                         object
macros                       object
ingredients                  object
temperature                  object
category                     object
dtype: object

In [35]:
#Drop rows with missing values for item_id
df = df[df.item_id.notnull()]

In [36]:
#Convert item_id into integer type
df.item_id = df.item_id.astype(int)

In [37]:
menu = pd.read_csv('../raw/meals.csv')

In [38]:
df.shape

(57494, 31)

In [39]:
data = df.groupby(['user_id','item_id']).quantity.sum().reset_index()

In [40]:
data.sample(5)

       user_id  item_id  quantity
3492      1828      229       1.0
8393      6067      377       1.0
29575    35007      186       1.0
13547    13433      470       1.0
9901      8351      443       1.0

In [41]:
sparse_mat = sparse.csr_matrix((data['quantity'], (data['user_id'], data['item_id'])))

In [42]:
#Number of possible interactions in the matrix
matrix_size = sparse_mat.shape[0]*sparse_mat.shape[1]

#Num of items with interactions
count_interactions = sparse_mat.size

#Compute matrix sparsity
sparsity = 100*(1 - (float(count_interactions)/float(matrix_size)))

print (sparsity)

99.89438704841044

In [43]:
# Set parameters
confidence_coef = 30
factors = 60
regularization = 0.1
iterations = 100

# Initialize model
model = implicit.als.AlternatingLeastSquares(factors=factors, regularization=regularization, iterations=iterations)

# Fit model
model.fit((sparse_mat.T*confidence_coef).astype('double'))

# Get user and item vectors from our trained model
user_vecs = model.user_factors
item_vecs = model.item_factors

WARNING:root:OpenBLAS detected. Its highly recommend to set the environment variable 'export OPENBLAS_NUM_THREADS=1' to disable its internal multithreading
100%|██████████| 100.0/100 [00:05<00:00, 18.91it/s]

In [44]:
def recommend(user_id, sparse_mat, user_vecs, item_vecs, num_items=15):
    user_interactions = sparse_mat[user_id,:].toarray()
    user_interactions = user_interactions.reshape(-1) + 1
    #Make items already interacted zero
    user_interactions[user_interactions > 1] = 0
    #Get dot product of user vector and all item vectors
    rec_vector = user_vecs[user_id,:].dot(item_vecs.T)
    
    #Scale dot product result between 0 and 1
    min_max = MinMaxScaler()
    rec_vector_scaled = min_max.fit_transform(rec_vector.reshape(-1,1))[:,0]
    #Get recommendation vector
    recommend_vector = user_interactions * rec_vector_scaled 
    #Sort into order of best recommendations
    item_idx = np.argsort(recommend_vector)[::-1][:num_items]
    
    #Start empty list to store titles and scores
    items = []
    scores = []
    #Append recommended item name and scores tolist
    for idx in item_idx:
        items.append(menu.name.loc[menu.id == idx].iloc[0])
        scores.append(recommend_vector[idx])
        
    recommendations = pd.DataFrame({'name': items, 'score': scores})

    return recommendations

In [45]:
menu.id = menu.id.astype(int)
menu = menu[menu['id'].isin(data.item_id)]

In [46]:
item_name = pd.DataFrame(menu[['id','name']])
data_with_name = data.merge(item_name,how='left',left_on='item_id',right_on='id')

In [47]:
for i in data['user_id'].sample(5):
    recommendations = recommend(i, sparse_mat, user_vecs, item_vecs)

    print( '\nTRANSACTION HISTORY FOR USER : ' + str(i) + '\n')
    print( data_with_name[data_with_name['user_id']==i][['name','item_id','quantity',]])
    print( '\nRECOMMEND FOLLOWING ITEMS \n')
    print( recommendations)

TRANSACTION HISTORY FOR USER : 26046

                             name  item_id  quantity
21678  Grilled Farm Fresh Chicken      336       1.0
21679          Thai Chicken Salad      368       1.0
21680      Dragon Well Basil Rice      377       1.0

RECOMMEND FOLLOWING ITEMS

                                                name     score
0                                     Wholemeal Pita  0.603194
1                        Cantonese Black Pepper Beef  0.507568
2                                    Thai Basil Beef  0.500173
3                                   Cinnamon Pumpkin  0.493481
4                           Dark Chocolate Lava Cake  0.431613
5                                       Chirashi-don  0.417793
6                  Slow Braised Beef and Duck Confit  0.415420
7                         Chilli Chimichurri Chicken  0.410333
8              Szechuan Pepper Sous‑Vide Duck Breast  0.406063
9                     Ginger Puree and Shiitake Dory  0.386212
10         Braised Oyster Sauce Mushroom and Tau Pok  0.385906
11                             Grilled Chicken Thigh  0.371932
12  Preparazzi presents: Chicken Confit Tomato Curry  0.371535
13                         Grilled Piri‑Piri Chicken  0.365456
14                     Osmanthus and Wolfberry Jelly  0.365052

TRANSACTION HISTORY FOR USER : 2726

                                                  name  item_id  quantity
4921                                       Green Ninja       82       1.0
4922  Warm Quinoa Salad with Roasted Autumn Vegetables      115       1.0
4923                                   Cheeky Flamingo      157       1.0
4924    Five-spice Tofu on Pea Shoots and Noodle Salad      170       2.0
4925                          Wakame Miso Sunomono Don      176       1.0

RECOMMEND FOLLOWING ITEMS

                                                 name     score
0                            Stuffed Goji Berry Tofu   0.833722
1                    Grilled Artichoke Baked Frittata  0.685694
2                                        Madame Grass  0.658961
3   Beets and Squash Mixed Grain with Oregano Tzat...  0.644840
4             Teriyaki Chicken Nasubi (Aubergine) Don  0.640020
5              Strawberry and Arugula Tabbouleh Salad  0.626671
6                                           Dry Laksa  0.614951
7         Spicy Quinoa and Oregano Sweet Potato Salad  0.603931
8                                    Lotus Leaf Rice   0.581307
9    Rosemary Seared Lamb on Thai Glass Noodle Salad   0.571993
10                     Cajun Chicken with Lentil Stew  0.568995
11             Teriyaki Chicken with Japanese Risotto  0.567609
12                            Grilled Beef Tenderloin  0.548706
13                                        Prawn Gyoza  0.548188
14                                    Beef Cheek Stew  0.546248

TRANSACTION HISTORY FOR USER : 20349

                                                    name  item_id  quantity
17833                        Pan‑seared Norwegian Salmon      334      10.0
17834                             Dragon Well Basil Rice      377       8.0
17835            Char‑grilled Zucchini and Couscous Bowl      444       7.0
17836                               Grilled Tiger Prawns      448      30.0
17837                                     Smoked Chicken      452      15.0
17838                               Olive‑crusted Ribeye      453      20.0
17839                                 Ribeye Shabu Shabu      455      20.0
17840              Grilled Garlic and Lime‑leaf Chicken       461      49.0
17841                4‑hour Braised  Gyuniku の Char Siew      475       4.0
17842                                Slow Cooked Salmon       484      38.0
17843  Roasted Summer Vegetables with King Oyster Mus...      487      15.0
17844                               Honey Chilli Chicken      488      45.0

RECOMMEND FOLLOWING ITEMS

                                        name     score
0                               Seared Toman  0.982428
1                     Cantonese Ngau Lam Poh  0.791720
2                Spicy Cold Marinated Tofu    0.775159
3                           Roasted Sea Bass  0.749064
4                         Grain Chicken Rice  0.734064
5             Caramelised Orange and Avocado  0.706347
6                   Grilled Thai BBQ Chicken  0.680942
7         Twice‑cooked Braised Beef Brisket   0.661854
8   CHEF'S SPECIAL INDIAN VEGETARIAN MEALBOX  0.653774
9                            Cheeky Flamingo  0.639193
10             Honey and Soy Roasted Tempeh   0.632917
11                       Mixed Summer Fruits  0.624177
12            Black Garlic Glazed Beef Cheek  0.621277
13     Sous‑vide Turkey on Chilled Capellini  0.614249
14                   Baked Chicken Meatballs  0.595180

TRANSACTION HISTORY FOR USER : 747

                                                   name  item_id  quantity
1309                                      Evil Flamingo       84       1.0
1310  Chipotle Chicken with Cranberry and Brie Couscous       92       1.0
1311                                       Chirashi-don      102       1.0
1312               Chimichurri Quinoa with Jerk Chicken      105       1.0
1313               Unadon with Winter Vegetables Nimono      106       1.0
1314             Deconstructed Togarashi Chicken Burger      114       1.0
1315                  Chicken Adobo with Barley Risotto      119       2.0
1316                                Samsui Chicken Rice      136       1.0

RECOMMEND FOLLOWING ITEMS

                                                 name     score
0                                    Lotus Leaf Rice   0.781071
1                                    Liquid Apple Pie  0.778597
2   Sliced Rib-eye and Japanese Pickle on Furikake...  0.764806
3           Cajun Chicken with Forgotten Grains Salad  0.731440
4                                  Grain Chicken Rice  0.728825
5                             Clam Chowder Black Rice  0.713821
6                      Vietnamese Street Noodle Salad  0.705694
7                                     Beef Cheek Stew  0.695197
8                                       Kinky Waikiki  0.685777
9                      Crab and Prawn Arrabiata Pasta  0.680674
10                                       Madame Grass  0.665036
11                          Cayenne Key Lime Seabass   0.658509
12  Smoked Pulled Pork with Red Cabbage and Raisin...  0.657013
13  Turkey Roulade with Walnut Stuffing and Cranbe...  0.647444
14                                    Cheeky Flamingo  0.635867

TRANSACTION HISTORY FOR USER : 30463

                   name  item_id  quantity
24994  White Beef Ragú       348       1.0

RECOMMEND FOLLOWING ITEMS

                                      name     score
0           Grilled Tangy Chipotle Chicken  0.791722
1              Cantonese Black Pepper Beef  0.695688
2               Cantonese Steamed Sea Bass  0.650637
3           Black Garlic Glazed Beef Cheek  0.638612
4                Roasted Carrot and Tomato  0.552975
5                          Thai Basil Beef  0.519332
6    MasterChef Asia: Butter‑Poached Toman  0.511245
7                Baked Herb‑Scented Salmon  0.503496
8            Honey and Soy Roasted Tempeh   0.495727
9                            Coconut Shake  0.491883
10          Caramelised Orange and Avocado  0.486436
11                      Ribeye Shabu Shabu  0.479975
12                  Cantonese Ngau Lam Poh  0.475583
13  Teriyaki Chicken with Japanese Risotto  0.474809
14               Cayenne Key Lime Seabass   0.473200